name: Create Release-Commit Git Tag
on:
  workflow_call:
    secrets:
      RELEASE:
        description: Release token
        required: true
    inputs:
      git_tag_name:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      git_tag_name:
        description: Git version tag (eg. v0.9.0)
        required: true

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE }}

      - name: Add git tag to release
        run: |
          TAG_COMMIT_HASH=$(git rev-parse HEAD)
          git tag ${{ inputs.git_tag_name }} ${TAG_COMMIT_HASH}
          git push origin ${{ inputs.git_tag_name }}
